import { createClient } from '@supabase/supabase-js';

const NEXT_PUBLIC_SUPABASE_URL=https://vgzlftijghwltdxrcnfk.supabase.co
const NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZnemxmdGlqZ2h3bHRkeHJjbmZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA3NjI3NTEsImV4cCI6MjA3NjMzODc1MX0.RFKE2hWUmRfRfzicIw7LD9EZy3YsXfr6eSLubZGQ_UM

export const supabase = createClient(NEXT_PUBLIC_SUPABASE_URL, NEXT_PUBLIC_SUPABASE_ANON_KEY);
